server:
  port: 30001 # 项目启动端口号

spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-nacos-consumer # 项目名称（nacos 注册的服务名）
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 5
  cloud:
    nacos:
      discovery:
        username: nacos # nacos 登录用户名
        password: nacos # nacos 密码
        server-addr: 127.0.0.1:8848 # nacos 服务端地址
        service:
          name: spring-cloud-nacos-provider

# 健康检测
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: false




