spring:
  application:
    name: spring-cloud-nacos-consumer # 项目名称（nacos 注册的服务名）
  cloud:
    nacos:
      discovery:
        username: nacos # nacos 登录用户名
        password: nacos # nacos 密码
        server-addr: 127.0.0.1:8848 # nacos 服务端地址
  main:
    allow-bean-definition-overriding: true

server:
  port: 20002 # 项目启动端口号

