server:
  port: 20001 # 项目启动端口号

spring:
  application:
    name: spring-cloud-nacos-provider # 项目名称（nacos 注册的服务名）
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        username: nacos # nacos 登录用户名
        password: nacos # nacos 密码
        server-addr: 127.0.0.1:8848 # nacos 服务端地址
    circuit:
      breaker:
        hystrix:
          enabled: true


# 健康检测
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: false
